module.exports = [
  'https://www.ambev.com.br/marcas/cervejas/adriatica',
  'https://www.ambev.com.br/marcas/cervejas/andes',
  'https://www.ambev.com.br/marcas/cervejas/antarctica',
  'https://www.ambev.com.br/marcas/cervejas/becks',
  'https://www.ambev.com.br/marcas/cervejas/berrio-do-piaui',
  'https://www.ambev.com.br/marcas/cervejas/bohemia-puro-malte',
  'https://www.ambev.com.br/marcas/cervejas/brahma/brahma-chopp',
  'https://www.ambev.com.br/marcas/cervejas/budweiser/budweiser',
  'https://www.ambev.com.br/marcas/cervejas/caracu',
  'https://www.ambev.com.br/marcas/cervejas/colorado/colorado-appia',
  'https://www.ambev.com.br/marcas/cervejas/corona',
  'https://www.ambev.com.br/marcas/cervejas/esmera-do-goias',
  'https://www.ambev.com.br/marcas/cervejas/franziskaner/franziskaner-hell',
  'https://www.ambev.com.br/marcas/cervejas/goose-island/goose-island-ipa',
  'https://www.ambev.com.br/marcas/cervejas/hoegaarden-wit-blanche',
  'https://www.ambev.com.br/marcas/cervejas/kona/kona-big-wave',
  'https://www.ambev.com.br/marcas/cervejas/leffe/leffe-blonde',
  'https://www.ambev.com.br/marcas/cervejas/legitima',
  'https://www.ambev.com.br/marcas/cervejas/magnifica',
  'https://www.ambev.com.br/marcas/cervejas/modelo',
  'https://www.ambev.com.br/marcas/cervejas/nossa-de-pernambuco',
  'https://www.ambev.com.br/marcas/cervejas/antarctica-original',
  'https://www.ambev.com.br/marcas/cervejas/patagonia/patagonia-bohemian-pilsener',
  'https://www.ambev.com.br/marcas/cervejas/polar',
  'https://www.ambev.com.br/marcas/cervejas/polar/polar-puro-malte-gaucho',
  'https://www.ambev.com.br/marcas/cervejas/serramalte',
  'https://www.ambev.com.br/marcas/cervejas/serrana',
  'https://www.ambev.com.br/marcas/cervejas/michelob-ultra',
  'https://www.ambev.com.br/marcas/cervejas/spaten',
  'https://www.ambev.com.br/marcas/cervejas/stella-artois',
  'https://www.ambev.com.br/marcas/cervejas/tres-fidalgas',
  'https://www.ambev.com.br/marcas/cervejas/wals/wals-42',
  'https://www.ambev.com.br/marcas/cervejas/abiuda-de-sergipe'
]

const failedUrl = []